### ISSUE TITLE
Additional MySQL schemas

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#14]
Here is a collection of other MySQL schemas:
https://github.com/ronaldbradford/schema

Maybe we want to add some of them.

**Comment by divyenduz** [comment]
`ezpublish`, `zencart`, `oscommerce` in public MySQL, we have most of the other ones that are interesting.

**Comment by janpio** [comment]
Thanks.

https://github.com/prisma/database-schema-examples/tree/master/mysql does not have the schemas yet.

**Comment by divyenduz** [comment]
https://dev.mysql.com/doc/index-other.html
