### ISSUE TITLE
OpenFootball

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#17]
https://github.com/openfootball/schema.sql

**Comment by divyenduz** [comment]
This looks like SQLite, where do we keep those? 
This is not MySQL. AFAIK.

**Comment by janpio** [comment]
Is it - how do you see the difference?

In general we have https://github.com/prisma/database-schema-examples/tree/master/sqlite but that is not built out yet similar to what I did in `mysql` and `postgres`. Does it make sense to create a server? Or does SQLite introspection only work with local files that one has to download from here then?

**Comment by divyenduz** [comment]
> Is it - how do you see the difference?

Got a hint from README, which says, `football.db`

The 2nd part is covered here: https://github.com/prisma/introspection-engine-output/issues/50
This will be available in the SQLite automation soon.
