### ISSUE TITLE
Finish datamodel examples

### ISSUE THREAD

**Issue by matthewmueller** [prisma/database-schema-examples#2]
A couple of the datamodel examples are blank, (cms, chinook, shakespear, sportsdb). There was errors when I tried to import them into psql. We'll need to fix those schemas and then run prisma-render

**Comment by ejoebstl** [comment]
FYI The [unit tests](https://github.com/prisma/prisma/tree/master/cli/packages/prisma-generate-schema/__tests__/blackbox/cases) in `prisma-generate-schema` have sanitized SQL dumps as well as Prisma Datamodel files for all these models.

**Comment by matthewmueller** [comment]
Thanks @ejoebstl! I just added the remaining examples in https://github.com/prisma/database-schema-examples/commit/a1b5c222c6effa3afb37a27d293018466de414e3
