### ISSUE TITLE
Helpdesk

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#22]
https://github.com/totaljs/helpdesk/blob/master/postgresql.sql

**Comment by divyenduz** [comment]
Available in public Postgres

**Comment by janpio** [comment]
No db "helpdesk" in public postgres - where should I look?
Also not in https://github.com/prisma/database-schema-examples/tree/master/postgres

**Comment by divyenduz** [comment]
I might have missed it, available now on server.
