### ISSUE TITLE
Aragon Notification Service

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#28]
https://github.com/aragonone/notification-service
https://github.com/aragonone/notification-service/tree/master/migrations
by @2color 

Asked for a dump of the actual SQL statements.

**Comment by divyenduz** [comment]
In out public DB.

**Comment by janpio** [comment]
MySQL? Postgres?
Can not find in https://github.com/prisma/database-schema-examples

**Comment by janpio** [comment]
@2color provided a PR, found it on public Postgres server then:
![image](https://user-images.githubusercontent.com/183673/71035067-003c3200-211b-11ea-8c1a-fedea865b2bc.png)
