### ISSUE TITLE
`allsquare` db might be broken

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#42]
See: https://github.com/prisma/introspection-engine-output/blob/automated/latest/mysql_public/allsquare_stderr.log

This indicates table `clubs` does not exist.

But per SQL dump it should:
https://github.com/prisma/database-schema-examples/blob/719c0f91c43e5d1f546e46e41bcbc57575df282f/mysql/allsquare/schema.sql#L743-L819

**Comment by janpio** [comment]
Import indeed seems to be incomplete:

![image](https://user-images.githubusercontent.com/183673/73581758-a99c7480-448a-11ea-8d50-a47110258d89.png)

**Comment by divyenduz** [comment]
Fixed this on the DB server.
