### ISSUE TITLE
Noalyss

### ISSUE THREAD

**Issue by janpio** [prisma/database-schema-examples#70]
https://www.noalyss.eu/

Could not figure out where/how to download, and if there might be a proper , but http://wiki.noalyss.eu/doc/annotated.html indicates if there is it might be interesting.

Could you please take a look @tomhoule?

**Comment by tomhoule** [comment]
The source code is at http://download.noalyss.eu/derniere-version/noalyss-7200.tar.gz

There is something that looks like an SQL dump inside `/noalyss/contrib/mono-dossier/`

Do you need more info @janpio ?

**Comment by janpio** [comment]
No, I think that would be enough for @divyenduz to start. Maybe some installation instructions maybe?

Update: Found http://wiki.noalyss.eu/doku.php?id=installation:installation_sous_linux which should include the most interesting stuff.
