### ISSUE TITLE
Scientific project "Complete data from the Barro Colorado 50-ha plot: 423617 trees, 35 years"

### ISSUE THREAD

**Issue by Jolg42** [prisma/database-schema-examples#98]
Source:
https://datadryad.org/stash/dataset/doi:10.15146/5xcp-0d46 (Archive with zip can be downloaded there)

This work is licensed under a CC0 1.0 Universal (CC0 1.0) Public Domain Dedication license. 

The raw data is one 880MB .sql file

![schema](https://user-images.githubusercontent.com/1328733/74724454-93d5d000-523c-11ea-9e6e-0175153f268d.png)

**Comment by janpio** [comment]
Please turn this into a PR with `schema.sql` and `data.sql` @pantharshit00.

**Comment by Jolg42** [comment]
@pantharshit00 See PR #99 ;-)
